BEGIN TRANSACTION;
CREATE TABLE areas (id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT DEFAULT '', titulo TEXT DEFAULT '', descripcion TEXT DEFAULT '');
INSERT INTO "areas" VALUES(1,'Niñera','Niñeras','Cuidado de bebés y niños');
INSERT INTO "areas" VALUES(2,'Cama adentro','Cama adentro','Vive en la casa del cliente');
INSERT INTO "areas" VALUES(3,'Cama afuera','Cama afuera','Entra y sale cada día');
INSERT INTO "areas" VALUES(4,'Por días','Por días','Limpieza algunos días a la semana');
INSERT INTO "areas" VALUES(5,'Cuidado de adulto mayor','Adulto mayor','Cuidado y compañía');
INSERT INTO "areas" VALUES(6,'Cocinera','Cocina','Preparación de comidas');
CREATE TABLE clientes (id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT DEFAULT '', dni TEXT DEFAULT '', telefono TEXT DEFAULT '', ocupacion TEXT DEFAULT '', direccion TEXT DEFAULT '', zona TEXT DEFAULT '', fecha_registro TEXT DEFAULT '', tipo_servicio TEXT DEFAULT '', sueldo_ofrecido TEXT DEFAULT '', horario TEXT DEFAULT '', dias_libres TEXT DEFAULT '', personas_hogar TEXT DEFAULT '', ninos TEXT DEFAULT '', mascotas TEXT DEFAULT '', tareas TEXT DEFAULT '', requisitos TEXT DEFAULT '', fecha_necesita TEXT DEFAULT '', notas TEXT DEFAULT '', estado TEXT DEFAULT '', meses_garantia TEXT DEFAULT '');
INSERT INTO "clientes" VALUES(1,'Cliente Ficticio Ñandú','10000001','999111222','','','','','Niñera','1500','','','','','','','','','','Colocado','2 meses');
INSERT INTO "clientes" VALUES(2,'Segundo Cliente Ficticio','','988777666','','','','','','','','','','','','','','','','Buscando','');
CREATE TABLE colocaciones (id INTEGER PRIMARY KEY AUTOINCREMENT, cliente_id TEXT DEFAULT '', trabajadora_id TEXT DEFAULT '', fecha_enlace TEXT DEFAULT '', estado TEXT DEFAULT '', notas TEXT DEFAULT '', sueldo_acordado TEXT DEFAULT '', porcentaje TEXT DEFAULT '', comision TEXT DEFAULT '', comision_pagada TEXT DEFAULT '', fecha_pago TEXT DEFAULT '', contrato_firmado TEXT DEFAULT '', fecha_firma TEXT DEFAULT '', firma_cliente TEXT DEFAULT '', firma_trabajadora TEXT DEFAULT '', firma_agencia TEXT DEFAULT '', garantia TEXT DEFAULT '', meses_garantia TEXT DEFAULT '', fecha_inicio TEXT DEFAULT '', fin_garantia TEXT DEFAULT '', reemplazo_de TEXT DEFAULT '', fecha_contrato TEXT DEFAULT '', puesto TEXT DEFAULT '', modalidad TEXT DEFAULT '', descanso TEXT DEFAULT '');
INSERT INTO "colocaciones" VALUES(1,'1','1','01/09/2026','Activa','','1500','','300.00','1','02/09/2026','1','01/09/2026','','','','Sí','2','01/09/2026','01/11/2026','','01/09/2026','Niñera','Cama afuera','Domingo');
CREATE TABLE trabajadoras (id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT DEFAULT '', dni TEXT DEFAULT '', telefono TEXT DEFAULT '', edad TEXT DEFAULT '', direccion TEXT DEFAULT '', zona TEXT DEFAULT '', tipo_servicio TEXT DEFAULT '', cama_adentro TEXT DEFAULT '', experiencia TEXT DEFAULT '', referencias TEXT DEFAULT '', doc_dni TEXT DEFAULT '', doc_antecedentes TEXT DEFAULT '', doc_salud TEXT DEFAULT '', doc_domicilio TEXT DEFAULT '', doc_referencias TEXT DEFAULT '', estado TEXT DEFAULT '', notas TEXT DEFAULT '');
INSERT INTO "trabajadoras" VALUES(1,'Trabajadora Ficticia José','20000002','999333444','','','','Niñera','','','','','','','','','Trabajando','');
INSERT INTO "trabajadoras" VALUES(2,'Otra Ficticia','','999555666','','','','','','','','','','','','','Disponible','');
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('areas',6);
INSERT INTO "sqlite_sequence" VALUES('clientes',2);
INSERT INTO "sqlite_sequence" VALUES('trabajadoras',2);
INSERT INTO "sqlite_sequence" VALUES('colocaciones',1);
COMMIT;
